#include <map>
#include <Windows.h>

std::map<int, char*> vkeys = {
	{ VK_CONTROL, "[CTRL]" },
	{ VK_LCONTROL, "[LCTRL]" },
	{ VK_RCONTROL, "[RCTRL]" },
	{ VK_SHIFT, "[SHIFT]" },
	{ VK_RSHIFT, "[RSHIFT]" },
	{ VK_LSHIFT, "[LSHIFT]" },
	{ VK_MENU, "[ALT]" },
	{ VK_LMENU, "[LALT]" },
	{ VK_RMENU, "[RALT]" },
	{ VK_CAPITAL, "[CAPSLOCK]" },
	{ VK_NUMLOCK, "[NUMLOCK]" },
	{ VK_LWIN, "[LWIN]" },
	{ VK_RWIN, "[RWIN]" },
	{ VK_PRIOR, "[PGUP]" }, // page up
	{ VK_NEXT, "[PGDOWN]" }, // page down
	{ VK_HOME, "[HOME]" },
	{ VK_END, "[END]" },
	{ VK_DELETE, "[DEL]" },
	{ VK_PAUSE, "[PAUSE]" },
	{ VK_SCROLL, "[SCROLLLOCK]" },
	{ VK_PRINT, "[PRINT]" },
	{ VK_UP, "[UP]" },
	{ VK_DOWN, "[DOWN]" },
	{ VK_LEFT, "[LEFT]" },
	{ VK_RIGHT, "[RIGHT]" },
	{ VK_ESCAPE, "[ESCAPE]" },
	{ VK_TAB, "[TAB]" },
	{ VK_F1, "[F1]" },
	{ VK_F2, "[F2]" },
	{ VK_F3, "[F3]" },
	{ VK_F4, "[F4]" },
	{ VK_F5, "[F5]" },
	{ VK_F6, "[F6]" },
	{ VK_F7, "[F7]" },
	{ VK_F8, "[F8]" },
	{ VK_F9, "[F9]" },
	{ VK_F10, "[F10]" },
	{ VK_F11, "[F11]" },
	{ VK_F12, "[F12]" }
};

std::map<char, char> shiftValues = {
	{ '`', '~' },
	{ '1', '!' },
	{ '2', '@' },
	{ '3', '#' },
	{ '4', '$' },
	{ '5', '%' },
	{ '6', '^' },
	{ '7', '&' },
	{ '8', '*' },
	{ '9', '(' },
	{ '0', ')' },
	{ '-', '_' },
	{ '=', '+' },
	{ '[', '{' },
	{ ']', '}' },
	{ '\\', '|' },
	{ ';', ':' },
	{ '\'', '\"' },
	{ ',', '<' },
	{ '.', '>' },
	{ '/', '?' }
};

std::map<int, char> shiftVirtKeys = {
	{ 0xC0, '`' },
	{ 0x31, '1' },
	{ 0x32, '2' },
	{ 0x33, '3' },
	{ 0x34, '4' },
	{ 0x35, '5' },
	{ 0x36, '6' },
	{ 0x37, '7' },
	{ 0x38, '8' },
	{ 0x39, '9' },
	{ 0x30, '0' },
	{ 0xBD, '-' },
	{ 0xBB, '=' },
	{ 0xDB, '[' },
	{ 0xDD, ']' },
	{ 0xDC, '\\' },
	{ 0xBA, ';' },
	{ 0xDE, '\'' },
	{ 0xBC, ',' },
	{ 0xBE, '.' },
	{ 0xBF, '/' },
};